### ISSUE TITLE
palladium crash

### ISSUE THREAD

**Issue by sorexm** [ThreeTAG/Palladium#104]
<img width="412" alt="ror 1" src="https://github.com/ThreeTAG/Palladium/assets/158231990/d87a0deb-ff7a-40a5-9803-b01e61f64980">

**Comment by sorexm** [comment]
help

**Comment by ThePhantomPig791** [comment]
could you give a crash report?

**Comment by sorexm** [comment]
Crash Report UUID: 1c69a47a-bba9-4e88-81d2-ada715b3b2bc

**Comment by Nexominer** [comment]
Did you install an addon?

**Comment by Nexominer** [comment]
If so you are missing the required mods

**Comment by sorexm** [comment]
thank you it was an addon of another version  that was crashing my game
