### ISSUE TITLE
Config for accessories button and powers button?

### ISSUE THREAD

**Issue by PlatypusOfHats** [ThreeTAG/Palladium#105]
It would be great if the inventory buttons for accessories and powers could be disabled/moved to prevent overlapping with buttons from other mods, or to just hide the buttons.
![2024-02-11_20 24 57](https://github.com/ThreeTAG/Palladium/assets/58866828/f7c48f24-cc87-476d-a0c1-ad5788cd59e0)

**Comment by Lucraft** [comment]
Added in https://github.com/ThreeTAG/Palladium/commit/f5680e1b49eadcddd678627cd8cdd1489aa1bad0
