### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by LukeFryWalker** [ThreeTAG/Palladium#107]
When i am going to download it, it says its a virus and that it couldnt verify package, is there a way to fix it? i will have to use ThreeCore if this issue isnt fixed

**Comment by Lucraft** [comment]
That's just your anti-virus overreacting since it's a jar file. If you've downloaded it from CurseForge/Modrinth it's safe.

**Comment by LukeFryWalker** [comment]
Mk, thanks!
