### ISSUE TITLE
Conflict with Apotheosis and Simply Swords

### ISSUE THREAD

**Issue by ZanderTurtle** [ThreeTAG/Palladium#115]
When in a pack with Apotheosis or Simply Swords, the game removes their socketing mechanic from the Smithing Table. Another conflict between this mod and Apotheosis is the removal many of the bookshelf crafting recipes such as the Hellshelves and the Melon Shelf. So far none of the recipe conflict mods I have tried have fixed theses issues.

**Comment by Lucraft** [comment]
Fixed, it wasnt really my fault, Placebo (library for Apotheosis) uses a mixin to inject recipe into game at the place as I do, therefore only one of those 2 mods was able to get its mixin working.
So, not necessarily Palladium's fault
