### ISSUE TITLE
Modpack (1.20.1, Forge 47.3.0) crashing on launch due to Palladium

### ISSUE THREAD

**Issue by swtbsl** [ThreeTAG/Palladium#121]
Using a custom modpack I made for Minecraft 1.20.1 on Forge 47.3.0, and the modpack crashes on launch/while loading. I removed Palladium and the modpack loaded fine. However, Palladium is required to run one of the key mods in the modpack. Is there something I can do to stop my game from crashing while keeping palladium?

**Comment by Lucraft** [comment]
Send the crash report, cant help otherwise

**Comment by swtbsl** [comment]
[crash-2024-06-10_12.09.14-fml.txt](https://github.com/user-attachments/files/15777862/crash-2024-06-10_12.09.14-fml.txt)
[latest.log](https://github.com/user-attachments/files/15777863/latest.log)

here's the crash report (there have been several crashes today with various issues as i've been messing around with mod stuff, the most recent one/ones are the crashes i'm talking abt) and the lates.log

**Comment by Lucraft** [comment]
That crash isnt Palladium-related:

Failure message: Mod chestlock requires storagedrawers any
		Currently, storagedrawers is not installed

**Comment by swtbsl** [comment]
that was an earlier crash that i already fixed, the most recent crashes have been palladium related

**Comment by Lucraft** [comment]
Yeah, but do you have a crash report of those recent crashes? Because that one is not from Palladium

**Comment by swtbsl** [comment]
that's the most recent crash report i can find in the modpack folder, i'm not sure why the most recent crashes aren't there

**Comment by Lucraft** [comment]
Nope :/
Maybe try to wipe your logs and crash-reports folder, then start the game again

**Comment by swtbsl** [comment]
wipe as in delete all the crash reports?

**Comment by Lucraft** [comment]
yes

**Comment by swtbsl** [comment]
tried it again today, and it is no longer crashing, no clear reason why it's working now. thanks for helping me tho, i appreciate it
