### ISSUE TITLE
Accessories crash bug

### ISSUE THREAD

**Issue by gabbigamers** [ThreeTAG/Palladium#123]
My friend crashes us and himself when we or he see his avatar.

[eg_hata_minecraft.txt](https://github.com/user-attachments/files/15921219/eg_hata_minecraft.txt)

This is the crash log. Also it says on the exit -1 that it is a rendering issue.

**Comment by awesomebossdj7** [comment]
accessories like the knockoff curios / trinkets? (also has a compat layer for both mods) yeah palladium doesnt exactly have a compat with it (curios dont work properly) but it shouldnt crash

**Comment by Lucraft** [comment]
> accessories like the knockoff curios / trinkets? (also has a compat layer for both mods) yeah palladium doesnt exactly have a compat with it (curios dont work properly) but it shouldnt crash

No, they are talking about Palladium's accessories

**Comment by Lucraft** [comment]
Fixed
