### ISSUE TITLE
First Person Animation Issues

### ISSUE THREAD

**Issue by KonaDolomite** [ThreeTAG/Palladium#17]
1. Looking in seemingly random directions will make the interpolation animation become choppy and lag in first person.

2. First person animations apply to third person in your inventory menu, and as well as when other players look at you in multiplayer.

3. First person hands cannot rotate in the x-axis

**Comment by Lucraft** [comment]
Was every bug with this fixed after I added the seperate first person animation stuff? @KonaDolomite
