### ISSUE TITLE
Render layer addition 

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#31]
add an option for slim arm models with render layers so like this 

{
    "type": "palladium:render_layer",
    "icon": "minecraft:blaze_rod",
    "title": "null",
    "bar_color": "light_gray",
    "hidden": true,
    "list_index": -1,
    "gui_position": "null",
    "description": "null",
    "render_layer": "namespace:render_layer_id"
    "render_layer_slim": "null"
}

If its null then it will be ignored but if it has a path then players with slim arm will see that model and not the regular one

**Comment by Lucraft** [comment]
You can technically achieve the same effect by linking to a compound render layer, which has two render layers inside of it. Each with a inverted/not inverted small arms conditions

**Comment by Lucraft** [comment]
@Nexominer You can also make the texture or model directly dependent on the skin type in the render layer, it's described here:
https://github.com/ThreeTAG/Palladium/wiki/Render-Layers#advanced-skin-typed-modelstextures

Its pretty much the best solution to this
