### ISSUE TITLE
Player texture for render layer

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#32]
Allow the current player skin to be a valid option for render layers ex “player” as the path and possibly an option for it to use the current skin change texture but not be forced by default

**Comment by Lucraft** [comment]
Do you need to be apply to apply transformers on the player textures aswell? Or would just be the plain use of the player texture be enough?

**Comment by Nexominer** [comment]
I just need to be able to have a model texture set as the players current texture

**Comment by Lucraft** [comment]
Perfect, then it's basically done
