### ISSUE TITLE
Compound render layer / render layer lan bug

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#36]
In lan / multiplayer compound render layers ( didn’t test with normal ones) that are linked to an animation sometimes do not display randomly sometimes will sometimes won’t ( I can stream this happening in a VC or try and record a video if needed)

**Comment by Nexominer** [comment]
This is most likely also an essentials only thing

**Comment by Nexominer** [comment]
Uhh yes

**Comment by Lucraft** [comment]
Does this still happen?

**Comment by Nexominer** [comment]
Ohhh I remember this but it’s caused when someone used an accessory from the palladium accessory system

**Comment by Nexominer** [comment]
I only know this happens caused I played with biz and he messed around with them and I noticed the issue
