### ISSUE TITLE
Possibly a custom Resistance Attribute

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#42]
The default armor attribute maxes at 30 FLAT now this is an issue since powers with resistance when you also wear armor well the armor now does nothing and it being maxed at 30 also messes up power stacking and a bit of a low number not allowing much freedoms for lets say less balanced powers

**Comment by Lucraft** [comment]
so basically this? https://www.curseforge.com/minecraft/mc-mods/attributefix

**Comment by Nexominer** [comment]
Uh bassicaly just would like smt like that to be in palladium if possible lol

**Comment by Lucraft** [comment]
Added, disabled tho if that mod is installed
