### ISSUE TITLE
Hud script bug

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#56]
If you have Multiple Hud scripts in 1 directory only 1 will load otherwise they have to be in different asset folders

**Comment by Spyeedy** [comment]
That's odd, it works fine for me. I'm using Palladium-fabric-1.19.2-4.0.0.0-Pre100-fabric.

I have 2 scripts in the `assets/spy_pack/kubejs_scripts` folder
![image](https://user-images.githubusercontent.com/16463199/221410423-ed115267-3a24-435b-9e2b-7747d59c7996.png)


My scripts
vertical_bar_overlay.js
![image](https://user-images.githubusercontent.com/16463199/221410380-a985f332-96fc-49ae-ba11-5d38cd65d73d.png)
some_overlay.js
![image](https://user-images.githubusercontent.com/16463199/221410394-1339a50b-f5b4-4d1a-8688-c8f61dd79cd1.png)

**Comment by Nexominer** [comment]
I had 2 bar overlays and they wouldn’t both load until I separated them

**Comment by Lucraft** [comment]
did you register the HUDs with different IDs?
