### ISSUE TITLE
A new section for the superpower command

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#64]
/superpower disable “power” @s
Or / superpower disable * @s  (would disable all the powers the person has) and the same for an enable section. imo this would be a super useful tool for powers that you wouldn’t want stacking with other powers but don’t won’t to straight up delete from the player with set.

**Comment by Lucraft** [comment]
I dont really see a use, if you need to disable/enable them from the player anyway, why not just use the add/set/remove?

**Comment by Nexominer** [comment]
Set straight deletes powers and that’s not very user friendly cause some powers can be very hard to get. But say I wanna have a transformation power with a model I don’t want the person stacking 53 powers onto that making them a god and I don’t wanna delete there powers

**Comment by Nexominer** [comment]
Cause we can’t just design commands for every power in every addon

**Comment by Nexominer** [comment]
For a transformation power you could do 
/superpower disable * 
/superpower enable test:transform
Then the person can use that power but not there others and when they turn back they can just use there powers agajn

**Comment by Lucraft** [comment]
I see. I would definitely not do this as a command tho, and rather in form on a power setting or ability. But not a priority for now, will come back to this later
