### ISSUE TITLE
Gecko entity bug

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#68]
When a mob has a gecko model they mimic certain player actions
https://media.essential.gg/33c5920e-6afa-4487-be0b-7f974da9e600

**Comment by Lucraft** [comment]
Does this still happen after the last update?

**Comment by Nexominer** [comment]
Yes oh I forgot to specify it’s none humanoids who mimic the action like crouching if a nearby player but it doesn’t always happen
