### ISSUE TITLE
Condition Bug: key-conditions inside of meta-conditions (like "or") don't work

### ISSUE THREAD

**Issue by ThePhantomPig791** [ThreeTAG/Palladium#76]
I believe this has been reported, even though I can't find it anywhere, but it's a minor bug (minor because there's an easy workaround) where having a key-activated condition inside of a condition like "or" will make the key condition not show up in the ability list, therefore making the ability unusable. 
A workaround is to make a dummy ability with the key condition, then in the "or" condition check for the thing you want to check for and the dummy ability being active

**Comment by Lucraft** [comment]
Due to limitations how the whole thing works, it's intended to have that limitation
