### ISSUE TITLE
Optional projectile option

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#80]
Projectiles can damage the user if they run through them so an option to disable this would be very nice

**Comment by Lucraft** [comment]
I can make it so that if you set the damage to 0, it wont try to hurt the entity at all

**Comment by Lucraft** [comment]
Oh nvm, I misunderstood it

**Comment by Nexominer** [comment]
No no what I ment was say you are using a super speed power and you have an attack you won’t to deal damage you mainly have to use projectiles and if the player runs into it the player takes damage

**Comment by Nexominer** [comment]
> Oh nvm, I misunderstood it

Ah lol
