### ISSUE TITLE
Render layer transparency issue

### ISSUE THREAD

**Issue by Nexominer** [ThreeTAG/Palladium#97]
When render layers have models with transparent parts inside a render layer the components above display from the outside of the transparent model however other render layers do not

https://github.com/ThreeTAG/Palladium/assets/106452655/b50853a1-5e5b-4dad-87bd-8539dec1e00f

**Comment by Lucraft** [comment]
I think this is just the typical Vanilla issue when it comes to semi-transparent things, not much I can do there. You could give it a try to re-order your layers to see if that changes the look of it

**Comment by Nexominer** [comment]
They are from seperate po
